openapi: 3.0.1
info:
  description: "MetaCritic"
  version: "1.0.6"
  title: "Projet final"

tags:
  - name: "MetaCritic"
    description: "gestion des Critics liees aux reviews"






paths:
  /users:
    get:
      tags:
        - Users
      summary: All Users
      description: Returns all users
      operationId: "getUsers" 
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Users'

    put:
      tags:
        - Users
      summary: Update User
      description: Update a user by his id
      operationId: "updateUser"
      requestBody:
        $ref: '#/components/requestBodies/User'
      responses:
        '201':
          description: users response

  /users/{id}:
    get:
      tags:
        - Users
      summary: Users By Id
      description: Returns a user by id
      operationId: "getUserById" 
      parameters:
        - $ref: '#/components/parameters/idInPath'
      responses:
        '200':
          description: users response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Users'
  
    delete:
      tags:
        - Users
      summary: Delete User By Id
      description: Delete a user by his id
      operationId: "DeleteUserById" 
      parameters:
        - $ref: '#/components/parameters/idInPath'
      responses:
        '204':
          description: users response


  /editors:
    get:
      tags:
        - Editors
      summary: All Editors
      description: Returns all editors
      operationId: "getEditors" 
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Editors'

    put:
      tags:
        - Editors
      summary: Update Editor
      description: Update a editor by his id
      operationId: "updateEditor"
      requestBody:
        $ref: '#/components/requestBodies/Editor'
      responses:
        '201':
          description: editors response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Editors'

  /editors/{id}:
    get:
      tags:
        - Editors
      summary: Editors By Id
      description: Returns a user by id
      operationId: "getEditorById" 
      parameters:
        - $ref: '#/components/parameters/idInPath'
      responses:
        '200':
          description: editors response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Editors'
                 
    delete:
      tags:
        - Editors
      summary: Delete Editor By Id
      description: Delete a editor by his id
      operationId: "DeleteEditorById" 
      parameters:
        - $ref: '#/components/parameters/idInPath'
      responses:
        '204':
          description: editors response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Editors'


  /criticsEditors:
    get:
      tags:
        - Critics Editor
      summary: All Critics Editors
      description: Returns all the Critics mayde by editors
      operationId: "getCriticsEditor" 
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/CriticsEditors'

    post:
      tags:
        - Critics Editor
      summary: Add Critics Editor
      description: Add Critic by a editor
      operationId: "addCriticEditor" 
      requestBody:
        $ref: '#/components/requestBodies/CriticsEditor'
      responses:
        '201':
          description: criticsEditors response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/CriticsEditors'

    put:
      tags:
        - Critics Editor
      summary: Update Critics Editor
      description: Update a Critic made by a editor by his id
      operationId: "updateCriticE" 
      requestBody:
        $ref: '#/components/requestBodies/CriticsEditor'
      responses:
        '201':
          description: rentals response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/CriticsEditors'

  /criticsEditors/{id}:
    get:
      tags:
        - Critics Editor
      summary: Critics Editors By Id
      description: Returns a Critic made by a editor by his id 
      operationId: "getCriticEditorById" 
      parameters:
        - $ref: '#/components/parameters/idInPath'
      responses:
        '200':
          description: criticsEditors response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/CriticsEditors'
                 
    delete:
      tags:
        - Critics Editor
      summary: Delete Critic Editors By Id
      description: Delete a Critic made by a editor by his id
      operationId: "DeleteCriticEditorById" 
      parameters:
        - $ref: '#/components/parameters/idInPath'
      responses:
        '204':
          description: criticsEditors response


  /reviews:
    get:
      tags:
        - Reviews
      summary: All Reviews
      description: Returns all the reviews mayde by editors
      operationId: "getReviews" 
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Reviews'

    post:
      tags:
        - Reviews
      summary: Add Review
      description: Add review
      operationId: "addReview" 
      requestBody:
        $ref: '#/components/requestBodies/Review'
      responses:
        '201':
          description: review response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Reviews'

    put:
      tags:
        - Reviews
      summary: Update Review
      description: Update a review by his id
      operationId: "updateReview" 
      requestBody:
        $ref: '#/components/requestBodies/Review'
      responses:
        '201':
          description: review response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Reviews'

  /reviews/{id}:
    get:
      tags:
        - Reviews
      summary: Reviews By Id
      description: Returns a review by his id
      operationId: "getreviewById" 
      parameters:
        - $ref: '#/components/parameters/idInPath'
      responses:
        '200':
          description: review response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Reviews'

    delete:
      tags:
        - Reviews
      summary: Delete Review By Id
      description: Delete a review by his id
      operationId: "DeleteReviewById" 
      parameters:
        - $ref: '#/components/parameters/idInPath'
      responses:
        '204':
          description: review response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Reviews'
  

  /criticsUsers:
    get:
      tags:
        - Critics User
      summary: All Critics Users
      description: Returns all the Critics mayde by user
      operationId: "getCriticsUsers" 
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/CriticsUsers'

    post:
      tags:
        - Critics User
      summary: Add Critics User
      description: Add Critic by a user
      operationId: "addCriticUser" 
      requestBody:
        $ref: '#/components/requestBodies/CriticsUser'
      responses:
        '201':
          description: criticsUsers response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/CriticsUsers'

    put:
      tags:
        - Critics User
      summary: Update Critics User
      description: Update a Critic made by a user by his id
      operationId: "updateCriticUser" 
      requestBody:
        $ref: '#/components/requestBodies/CriticsUser'
      responses:
        '201':
          description: criticsUsers response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/CriticsUsers'

  /criticsUsers/{id}:
    get:
      tags:
        - Critics User
      summary: Critics Users by id
      description: Returns a Critic made by a user by his id 
      operationId: "getCriticUserById" 
      parameters:
        - $ref: '#/components/parameters/idInPath'
      responses:
        '200':
          description: criticsUsers response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/CriticsUsers'
  
    delete:
      tags:
        - Critics User
      summary: Delete Critics User by id
      description: Delete a Critic made by a user by his id
      operationId: "DeleteCriticUserById" 
      parameters:
        - $ref: '#/components/parameters/idInPath'
      responses:
        '204':
          description: criticsUsers response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/CriticsUsers'


  /register/SignUp:
    post:
      tags:
        - Sign Up
      summary: Sign Up
      description: Sign Up
      operationId: "signUp" 
      requestBody:
        $ref: '#/components/requestBodies/SignUp'
      responses:
        '201':
          description: criticsUsers response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/SignUp'
    
    
  /register/SignIn:  
    post:
      tags:
        - Sign In
      summary: Sign In
      description: Sign In
      operationId: "signIn" 
      requestBody:
        $ref: '#/components/requestBodies/SignIn'
      responses:
        '200':
          description: criticsUsers response
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/SignIn'




components:
  parameters:
    idInPath:
      required: true
      name: id
      in: path
      schema:
        type: integer


  requestBodies:

    User:
      description: A JSON object containing an user
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Users'
          examples:
            userExample:
              $ref: '#/components/examples/Users'

    Editor:
      description: A JSON object containing an editor
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/examples/Editors'
          examples:
            editorExample:
              $ref: '#/components/examples/Editors'

    CriticsEditor:
      description: A JSON object containing a critic from an editor
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/examples/CriticsEditors'
          examples:
            criticsEditorExample:
              $ref: '#/components/examples/CriticsEditors'

    Review:
      description: A JSON object containing a review
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/examples/Reviews'
          examples:
            reviewsExample:
              $ref: '#/components/examples/Reviews'

    CriticsUser:
      description: A JSON object containing a critic from an user
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/examples/CriticsUsers'
          examples:
            criticsUserExample:
              $ref: '#/components/examples/CriticsUsers'
              
    SignUp:
      description: A JSON object containing a sign up
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/examples/SignUp'
          examples:
            criticsUserExample:
              $ref: '#/components/examples/SignUp'
              
    SignIn:
      description: A JSON object containing a sign in
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/examples/SignIn'
          examples:
            criticsUserExample:
              $ref: '#/components/examples/SignIn'


  schemas:
    Users:
      type: object
      properties:
        idU:
          type: integer
          format: int64
          example: 1
        pseudo:
          type: string
          example: user_1
        email:
          type: string
          example: user_1@gmail.com

    Editors:
      type: object
      properties:
        idE:
          type: integer
          format: int64
          example: 1
        pseudo:
          type: string
          example: editor_1
        email:
          type: string
          example: editor_1@gmail.com

    CriticsEditors:
      type: object
      properties:
        idC:
          type: integer
          format: int64
          example: 1
        evaluation:
          type: string
          example: bien
        noteE:
          type: integer
          format: int64
          example: 8
        date:
          type: string 
          format: date
          example: 2023-12-26
        idE:
          type: integer
          format: int64
          example: 1

    Reviews:
      type: object
      properties:
        idR:
          type: integer
          format: int64
          example: 1
        avgU:
          type: number 
          format: int64
          example: 9.8   
        description:
          type: string
          example: "Take on the role of James Bond as played by Daniel Craig in all new SKYFALL levels. Unlock three new single player levels following the storyline of the SKYFALL movie. Levels take place in Istanbul and Shanghai as the player (Bond) attempts to track down "
        title:
          type: string
          example: "007 Legends: Skyfall"
        release:
          type: string
          example: "2012/11/20"
        idC:
          type: integer
          format: int64
          example: 1

    CriticsUsers:
      type: object
      properties:
        idR:
          type: integer
          format: int64
          example: 1
        idU:
          type: integer
          format: int64
          example: 1
        comment:
          type: string
          example: Super jeu
        noteU:
          type: integer
          format: int64
          example: 10
        date:
          type: string 
          format: date
          example: 2023-12-26
          
    SignUp:
      type: object
      properties:
        success:
          type: string
          example: true
        message:
          type: string
          example: User created !
    
    SignIn:
      type: object
      properties:
        success:
          type: string
          example: true
        token:
          type: string
          example: eyJhbGciOiqdqdk1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDM2MDU2NzQsImV4cCI6MTcwMzYwOTI3NH0.JSK5U2k-5WxCW3svHIOP4I9X4ehOUX8iWiWdcO1BQQc
          

  examples:
    Reviews:
      summary: An example of a review
      value:
        avgU: 9.8
        title: "007 Legends: Skyfall"
        idC: 1

    CriticsEditors:
      summary: An example of a Critic made by a editor
      value:
        evaluation: "bien"
        noteE: 8
        idE: 1

    CriticsUsers:
      summary: An example of a Critic made by a user
      value:
        idR: 1
        idU: 1
        comment: "Super jeu"
        noteU: 1
        date: "2023-12-26"

    Users:
      summary: An example of a user
      value:
        idU: 1
        pseudo: "user_1"
        email: "user_1@gmail.com"
        password: "user_mdp"

    Editors:
      summary: An example of a editor
      value:
        idE: 1
        pseudo: "editor_1"
        email: "editor_1@gmail.com"
        password: "editor_mdp"
        
    SignUp:
      summary: An example of a sign up
      value:
        pseudo: "user_1"
        email: "user_1@gmail.com"
        password: "user_mdp"
        
    SignIn:
      summary: An example of a sign in
      value:
        email: "user_1@gmail.com"
        password: "user_mdp"



